biolink_version: 4.2.5
kraken_version: 1.0.0
steps:
  harmonize: True
  integrate: True
  metagraph: False
  postprocess: False

sources:
  kg2:
    # RTX-KG2 has separate nodes and edges files
    nodes_input: "input_data/kg2/kg2.10.2/kg2c-2.10.2-v1.0-nodes-test.jsonl"
    edges_input: "input_data/kg2/kg2.10.2/kg2c-2.10.2-v1.0-edges-test.jsonl"
    harmonized_output:
      nodes: "artifacts/harmonized/kg2/nodes.jsonl"
      edges: "artifacts/harmonized/kg2/edges.jsonl"
    enabled: True
    allow_merge: False

  lipidmaps:
    input_file: "input_data/lipidmaps/structures.sdf"
    harmonized_output:
      nodes: "artifacts/harmonized/lipidmaps/nodes.jsonl"
      edges: "artifacts/harmonized/lipidmaps/edges.jsonl"
    enabled: True
    allow_merge: False

  umls:
    input_file: "input_data/umls/LOINC_PART_UMLS.tsv"
    harmonized_output:
      nodes: "artifacts/harmonized/umls/nodes.jsonl"
      edges: "artifacts/harmonized/umls/edges.jsonl"
    enabled: True
    allow_merge: False

  spoke:
    # SPOKE has mixed nodes and edges in one file
    input_file: "input_data/spoke/v6/spokeV6_test_human.jsonl"
    harmonized_output:
      nodes: "artifacts/harmonized/spoke/nodes.jsonl"
      edges: "artifacts/harmonized/spoke/edges.jsonl"
    enabled: True
    allow_merge: False

integration:
  output_directory: "artifacts/integrated/"
  primary_source: "kg2"  # Source to use for equivalency mappings (base)

post_processing:
  arango_export:
    output_directory: "artifacts/export/arango/"

  biomapper_export:
    output_directory: "artifacts/export/biomapper/"
