kraken_version: 2.1.0
biolink_version: 4.2.5
log_level: INFO
steps:
  harmonize: True
  integrate: True
  postprocess: True
options:
  metagraph_creation: True
  validate_output: True
  validation_only: False
  include_sources: []
  exclude_sources: ["clingen", "molepro"]

# Base directory path to use for all input/output files (should be absolute path)
# Set to null to use kraken project root as base path
base_path: "/Volumes/AmySSD/kraken-data"

harmonization:
  output_directory: "artifacts/harmonized/"
  zip_inputs_after: False
  validate_output: True

integration:
  output_directory: "artifacts/integrated/"

metagraph:
  output_directory: "artifacts/metagraphs"

post_processing:
  test_export:
    output_directory: "artifacts/integrated/"
    num_edges: 10000

sources:
  kg2:
    version: "2.10.2"
    nodes_input: "input_data/kg2/kg2.10.2/kg2c-2.10.2-v1.0-nodes.jsonl"
    edges_input: "input_data/kg2/kg2.10.2/kg2c-2.10.2-v1.0-edges.jsonl"

  robokop:
    version: "june2025"
    nodes_input: "input_data/robokop/june2025/nodes.jsonl"
    edges_input: "input_data/robokop/june2025/edges.jsonl"

  translator-kg-open:
    version: "2026_07_19"
    nodes_input: "input_data/translator-kg-open/2026_07_19/nodes.jsonl"
    edges_input: "input_data/translator-kg-open/2026_07_19/edges.jsonl"

  ncbigene:
    version: "accessed_2026-08-31"
    input_file: "input_data/ncbigene"

  microbiome-kg:
    version: "2.1.0"
    nodes_input: "input_data/microbiome-kg/Microbiome_KG_nodes_v2.1.0.tsv"
    edges_input: "input_data/microbiome-kg/Microbiome_KG_edges_p2.1.0.tsv"

  multiomics-kg:
    version: "2.1.0"
    nodes_input: "input_data/multiomics-kg/Multiomics_KG_nodes_v2.1.0.tsv"
    edges_input: "input_data/multiomics-kg/Multiomics_KG_edges_p2.1.0.tsv"

  umls:
    version: "2025AA"
    input_file: "input_data/umls/LOINC_PART_UMLS.tsv"

  lipidmaps:
    version: "accessed_2026-08-07"
    input_file: "input_data/lipidmaps/structures.sdf"

  refmet:
    version: "accessed_2026-08-07"
    input_file: "input_data/refmet/refmet.csv"

  loinc:
    version: "2.82"
    input_file: "input_data/loinc/Loinc_2.82"

  cdes:
    version: "accessed_2026-07-29"
    input_file: "input_data/cdes/SearchExport.json"

  pgs-catalog:
    version: "2026-07-29"
    input_file: "input_data/pgs-catalog/pgs_all_metadata.xlsx"

  bio-bmi:
    version: "2023"  # Watanabe et al. Nat Med 2023 (doi:10.1038/s41591-023-02248-0)
    input_file: "input_data/bio-bmi"

  bio-age:
    version: "2019"  # Earls et al. J Gerontol A 2019 (doi:10.1093/gerona/glz220)
    input_file: "input_data/bio-age"


  clingen:
    version: null  # TODO: fill in ClinGen release/download date
    input_file: "input_data/clingen/acmg_actionability.json"